# Generated by Django 4.2.4 on 2023-08-14 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=' Blog!', max_length=255),
        ),
    ]
